### ISSUE TITLE
Build fails with strict-aliasing violations

### ISSUE THREAD

**Issue by eli-schwartz** [LunarG/gfxreconstruct#2358]
I tried to build with the following *FLAGS to optimize the build: `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

The -Werror=* flags are important to detect cases where the compiler can try to optimize based on assuming Undefined Behavior (UB) cannot happen, and miscompile code that has UB in it. strict-aliasing issues are always bad but LTO can make them even worse.

I got this error:
```
[23/39] /usr/bin/x86_64-pc-linux-gnu-g++ -DGFXRECON_ENABLE_LZ4_COMPRESSION -DGFXRECON_ENABLE_PNG_SCREENSHOT -DGFXRECON_ENABLE_ZLIB_COMPRESSION -DGFXRECON_ENABLE_ZSTD_COMPRESSION -DPAGE_GUARD_ENABLE_UCONTEXT_WRITE_DETECTION -DPROJECT_VERSION_HEADER_FILE=\"project_version_RelWithDebInfo.h\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_NO_PROTOTYPES -DVK_USE_PLATFORM_DISPLAY_KHR -DVK_USE_PLATFORM_HEADLESS -DXR_USE_GRAPHICS_API_VULKAN -D_FILE_OFFSET_BITS=64 -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999_build -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/build -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/SPIRV-Reflect -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/stb -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/Vulkan-Headers/include -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/SPIRV-Headers/include -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/nlohmann-json/include  -pipe -ggdb -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o -MF framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o.d -o framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o -c /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/generated/generated_vulkan_api_call_encoders.cpp
FAILED: framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DGFXRECON_ENABLE_LZ4_COMPRESSION -DGFXRECON_ENABLE_PNG_SCREENSHOT -DGFXRECON_ENABLE_ZLIB_COMPRESSION -DGFXRECON_ENABLE_ZSTD_COMPRESSION -DPAGE_GUARD_ENABLE_UCONTEXT_WRITE_DETECTION -DPROJECT_VERSION_HEADER_FILE=\"project_version_RelWithDebInfo.h\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_NO_PROTOTYPES -DVK_USE_PLATFORM_DISPLAY_KHR -DVK_USE_PLATFORM_HEADLESS -DXR_USE_GRAPHICS_API_VULKAN -D_FILE_OFFSET_BITS=64 -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999_build -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/build -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external -I/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/SPIRV-Reflect -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/stb -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/Vulkan-Headers/include -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/SPIRV-Headers/include -isystem /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/external/nlohmann-json/include  -pipe -ggdb -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o -MF framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o.d -o framework/encode/CMakeFiles/gfxrecon_encode.dir/__/generated/generated_vulkan_api_call_encoders.cpp.o -c /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/generated/generated_vulkan_api_call_encoders.cpp
In file included from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/util/thread_data.h:28,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/command_writer.h:29,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/capture_manager.h:29,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/api_capture_manager.h:28,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/vulkan_capture_manager.h:28,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/custom_vulkan_encoder_commands.h:28,
                 from /var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/generated/generated_vulkan_api_call_encoders.cpp:32:
/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/parameter_encoder.h: In member function ‘void gfxrecon::encode::ParameterEncoder::EncodeLUIDValue(LUID)’:
/var/tmp/portage/dev-debug/gfxreconstruct-9999/work/gfxreconstruct-9999/framework/encode/parameter_encoder.h:80:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   80 |     void EncodeLUIDValue(LUID value) { EncodeValue(*reinterpret_cast<int64_t*>(&value)); }
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
ninja: build stopped: cannot make progress due to previous errors.
 * ERROR: dev-debug/gfxreconstruct-9999::gentoo failed (compile phase):
 *   ninja -v -k0 failed
```

Originally reported upstream: https://bugs.gentoo.org/956019
Reproduced now with git `dev`.
Exhaustive build log: [build.log](https://github.com/user-attachments/files/21726236/build.log)

**Comment by thesamesam** [comment]
Introduced by eabf61d2ea40d389675842fd26127a483bda15a6 (cc @jzulauf-lunarg). Just use memcpy if you can't use std::bit_cast from C++20.

**Comment by mattst88** [comment]
I've fixed this with https://github.com/LunarG/gfxreconstruct/pull/2559 but cannot get anyone to take a look or run the CI.
