### ISSUE TITLE
not compiling against gcc 11

### ISSUE THREAD

**Issue by oneforall2** [LunarG/gfxreconstruct#544]
from /tmp/gfxreconstruct-sdk-1.2.176/framework/generated/generated_vulkan_struct_handle_wrappers.cpp:29:
In static member function ‘static _Tp* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(const _Tp*, const _Tp*, _Tp*) [with _Tp = unsigned char; bool _IsMove = true]’,
    inlined from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = true; _II = unsigned char*; _OI = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_algobase.h:495:30,
    inlined from ‘_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = true; _II = unsigned char*; _OI = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_algobase.h:522:42,
    inlined from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = true; _II = unsigned char*; _OI = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_algobase.h:529:31,
    inlined from ‘_OI std::copy(_II, _II, _OI) [with _II = std::move_iterator<unsigned char*>; _OI = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_algobase.h:620:7,
    inlined from ‘static _ForwardIterator std::__uninitialized_copy<true>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<unsigned char*>; _ForwardIterator = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_uninitialized.h:110:27,
    inlined from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<unsigned char*>; _ForwardIterator = unsigned char*]’ at /usr/include/c++/11.1.0/bits/stl_uninitialized.h:151:15,
    inlined from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<unsigned char*>; _ForwardIterator = unsigned char*; _Tp = unsigned char]’ at /usr/include/c++/11.1.0/bits/stl_uninitialized.h:333:37,
    inlined from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = unsigned char*; _ForwardIterator = unsigned char*; _Allocator = std::allocator<unsigned char>]’ at /usr/include/c++/11.1.0/bits/stl_uninitialized.h:355:2,
    inlined from ‘void std::vector<_Tp, _Alloc>::_M_range_insert(std::vector<_Tp, _Alloc>::iterator, _ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const unsigned char*; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/11.1.0/bits/vector.tcc:783:9,
    inlined from ‘void std::vector<_Tp, _Alloc>::_M_insert_dispatch(std::vector<_Tp, _Alloc>::iterator, _InputIterator, _InputIterator, std::__false_type) [with _InputIterator = const unsigned char*; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/11.1.0/bits/stl_vector.h:1665:19,
    inlined from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::const_iterator, _InputIterator, _InputIterator) [with _InputIterator = const unsigned char*; <template-parameter-2-2> = void; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/11.1.0/bits/stl_vector.h:1383:22,
    inlined from ‘uint8_t* gfxrecon::encode::HandleUnwrapMemory::GetFilledBuffer(const uint8_t*, size_t)’ at /tmp/gfxreconstruct-sdk-1.2.176/framework/encode/vulkan_handle_wrapper_util.h:80:32,
    inlined from ‘T* gfxrecon::encode::MakeUnwrapStructs(const T*, size_t, gfxrecon::encode::HandleUnwrapMemory*) [with T = VkCommandBufferInheritanceInfo]’ at /tmp/gfxreconstruct-sdk-1.2.176/framework/generated/generated_vulkan_struct_handle_wrappers.h:375:63,
    inlined from ‘const T* gfxrecon::encode::UnwrapStructPtrHandles(const T*, gfxrecon::encode::HandleUnwrapMemory*) [with T = VkCommandBufferInheritanceInfo]’ at /tmp/gfxreconstruct-sdk-1.2.176/framework/generated/generated_vulkan_struct_handle_wrappers.h:385:45,
    inlined from ‘void gfxrecon::encode::UnwrapStructHandles(VkCommandBufferBeginInfo*, gfxrecon::encode::HandleUnwrapMemory*)’ at /tmp/gfxreconstruct-sdk-1.2.176/framework/generated/generated_vulkan_struct_handle_wrappers.cpp:338:57:
/usr/include/c++/11.1.0/bits/stl_algobase.h:431:30: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing 1 or more bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  431 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);

**Comment by Samsuper12** [comment]
This should be fixed by #562

**Comment by bradgrantham-lunarg** [comment]
I couldn't reproduce this against GCC 11.1.0 on Ubuntu 20.04.  What version of GCC was on this system, and how did you build?

**Comment by Samsuper12** [comment]
> I couldn't reproduce this against GCC 11.1.0 on Ubuntu 20.04. What version of GCC was on this system, and how did you build?

With GCC 11.1.0-1 (newer than just 11.1.0) the problem is gone.

**Comment by bradgrantham-lunarg** [comment]
Looking into this code a little more in depth, both of the instances mentioned here and in #562 boil down essentially to:
```
    std::vector<uint8_t> buffer;
    uint8_t *bytes;
    size_t count;
    [...]
    buffer.insert(buffer.end(), bytes, bytes + count);
```
Unless I'm very mistaken, that's a commonly used idiom.

I've created a Compiler Explorer excerpt from `TraceManager::WriteSetDeviceMemoryPropertiesCommand()` at https://godbolt.org/z/7EYfhcfMG. That excerpted code appears to work fine in g++ 11.1 and 11.2.

I'm very inclined to think this is a one-off bug in a spot release of g++ 11.1 and not an issue we should worry about handling with an #ifdef block.

**Comment by bradgrantham-lunarg** [comment]
Hm, maybe spoke too soon.  I'm still pretty convinced that this is a bug, but lack the definitive reference to state it.  I've created a Compiler Explorer snippet at https://godbolt.org/z/6PqbcPMPM that shows a similar problem in GCC 11.2, I see the bug at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100366 is not fixed yet, and I'll see what else I can find.
Still, if @Samsuper12 can verify the problem goes away with 11.1.0-1, I think I'll recommend we close this and #562 .

**Comment by Samsuper12** [comment]
> Still, if @Samsuper12 can verify the problem goes away with 11.1.0-1, I think I'll recommend we close this and #562 .

Oops.. Sorry, but the problem is available with `-DCMAKE_BUILD_TYPE=Release`, but with `Debug` is gone.
@bradgrantham-lunarg Can you please build debug version?

**Comment by bradgrantham-lunarg** [comment]
Yes, I do see it with 11.1.0-1ubuntu1 with Release.  We'll discuss internally.

(And, sorry, I think I meant "if @oneforall2 can verify the problem goes away with 11.1.0-1"!  But we can now repro here, so no need.)

**Comment by bradgrantham-lunarg** [comment]
Close as issue is reported fixed by @Samsuper12

**Comment by bradgrantham-lunarg** [comment]
The fix for this issue was lost in 7a0573c882ac61cc222f20a40df7c87b26143a5a as part of a merge.  The fix remains the same - move from `scrastch_buffer.insert(...)` to `std::copy(..., std::back_inserter(scratch_buffer))`

**Comment by bradgrantham-lunarg** [comment]
Fixed by #676
