### ISSUE TITLE
Add a Python version check to helper scripts

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#962]
The customer-visible scripts `gfxrecon.py`, `gfxrecon-capture.py`, and `gfxrecon-capture-vulkan.py` should do a Python version check early in the script.

Our internal users have had issues where they were using an earlier version of Python than the script required, and the default error message isn't very helpful, e.g.:
```
>  python C:\VulkanSDK\1.3.239.0\Bin\gfxrecon.py capture-vulkan D:\VulkanDev\SaschaWillemsVulkan\build\bin\Debug\bloom.exe
Executing program D:\VulkanDev\SaschaWillemsVulkan\build\bin\Debug\bloom.exe
Traceback (most recent call last):
  File "C:\VulkanSDK\1.3.239.0\Bin\gfxrecon-capture-vulkan.py", line 339, in <module>
    result = subprocess.run(args.program_and_args, capture_output=True)
  File "C:\Users\dustin\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
PS C:\Users\dustin> python C:\VulkanSDK\1.3.239.0\Bin\gfxrecon-capture-vulkan.py D:\VulkanDev\SaschaWillemsVulkan\build\bin\Debug\bloom.exe
Executing program D:\VulkanDev\SaschaWillemsVulkan\build\bin\Debug\bloom.exe
Traceback (most recent call last):
  File "C:\VulkanSDK\1.3.239.0\Bin\gfxrecon-capture-vulkan.py", line 339, in <module>
    result = subprocess.run(args.program_and_args, capture_output=True)
  File "C:\Users\dustin\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by bradgrantham-lunarg** [comment]
We should do such a test.  We're somewhat lucky that the first Google search result for `unexpected keyword argument 'capture_output'` is a Stack Overflow post noting that Python 3.7 is the first version to support `capture_output`.

What does the Pythonic version of the test look like?

**Comment by lunarpapillo** [comment]
Something like:
```
if sys.version_info() < (3, 7):
    log.error("Python 3.7 or better is required; you're using: %s", sys.version)
    sys.exit(1)
```

**Comment by locke-lunarg** [comment]
It should add in all python code? or only `gfxrecon.py`?

**Comment by bradgrantham-lunarg** [comment]
3.7 was released in 2018.  3.8 was released in 2019.  We assume Visual Studio 2019, so I suggest we might consider assuming Python 3.8.

ff707ac3 added code to the generators to make them compatible with < 3.9, so it's possible 3.8 is just what I knew worked on my machine at the time.  The generators may very well also work with 3.7.

`CONTRIBUTING.md` has been updated several times in 2022 and 2023 according to the `git log`.  I more-or-less trust it to be up to date.

I don't immediately see a duplicate section.  If you message me with the section I'll update it and push it and update the copyright.

**Comment by bradgrantham-lunarg** [comment]
The generators require at least Python 3.8.

```
Generating generated_vulkan_enum_to_json.cpp
Traceback (most recent call last):
  File "/home/lunarg/brad/gfxreconstruct/framework/generated/vulkan_generators/gencode.py", line 50, in <module>
    from vulkan_decoder_body_generator import VulkanDecoderBodyGenerator, VulkanDecoderBodyGeneratorOptions
  File "/home/lunarg/brad/gfxreconstruct/framework/generated/vulkan_generators/vulkan_decoder_body_generator.py", line 25, in <module>
    from base_generator import BaseGenerator, BaseGeneratorOptions, write
  File "/home/lunarg/brad/gfxreconstruct/framework/generated/vulkan_generators/base_generator.py", line 92
    def removesuffix(self: str, suffix: str, /) -> str:
                                             ^
SyntaxError: invalid syntax
```
